// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using home_finance.API.Data;

#nullable disable

namespace home_finance.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260112232939_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("home_finance.API.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Purpose")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PurposeDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Remuneração",
                            Purpose = 1,
                            PurposeDescription = ""
                        },
                        new
                        {
                            Id = 2,
                            Description = "Mantimentos",
                            Purpose = 0,
                            PurposeDescription = ""
                        },
                        new
                        {
                            Id = 3,
                            Description = "Contas",
                            Purpose = 0,
                            PurposeDescription = ""
                        },
                        new
                        {
                            Id = 4,
                            Description = "Entretenimento",
                            Purpose = 0,
                            PurposeDescription = ""
                        },
                        new
                        {
                            Id = 5,
                            Description = "Outros",
                            Purpose = 2,
                            PurposeDescription = ""
                        });
                });

            modelBuilder.Entity("home_finance.API.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 20,
                            Name = "Pedro"
                        },
                        new
                        {
                            Id = 2,
                            Age = 19,
                            Name = "Nathalia"
                        },
                        new
                        {
                            Id = 3,
                            Age = 16,
                            Name = "Isac"
                        },
                        new
                        {
                            Id = 4,
                            Age = 30,
                            Name = "Luiz"
                        },
                        new
                        {
                            Id = 5,
                            Age = 60,
                            Name = "Paulo"
                        },
                        new
                        {
                            Id = 6,
                            Age = 23,
                            Name = "Dielle"
                        });
                });

            modelBuilder.Entity("home_finance.API.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdateAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PersonId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 5000.00m,
                            CategoryId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Salário Pedro",
                            PersonId = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 1000.00m,
                            CategoryId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Salário Nathalia",
                            PersonId = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 1000.00m,
                            CategoryId = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Comidas do Mês",
                            PersonId = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            Amount = 200.00m,
                            CategoryId = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Produtos de Higiene",
                            PersonId = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            Amount = 80.50m,
                            CategoryId = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Conta de luz",
                            PersonId = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            Amount = 100.00m,
                            CategoryId = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cinema",
                            PersonId = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            Amount = 2000.00m,
                            CategoryId = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Troca de Pneu do Carro",
                            PersonId = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 8,
                            Amount = 750.00m,
                            CategoryId = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Remédios para Paulo",
                            PersonId = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 9,
                            Amount = 400.00m,
                            CategoryId = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bebidas do Churrasco",
                            PersonId = 6,
                            Type = 0
                        });
                });

            modelBuilder.Entity("home_finance.API.Models.Transaction", b =>
                {
                    b.HasOne("home_finance.API.Models.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("home_finance.API.Models.Person", "Person")
                        .WithMany("Transactions")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("home_finance.API.Models.Category", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("home_finance.API.Models.Person", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
